[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "miarka_processing_service"
description = "Service to perform operations on miarka."
readme = "README.md"
keywords = ["bioinformatics"]
authors = [{ name = "CGU, Uppsala University" }]
requires-python = ">=3.12"
dependencies = [
    "arteria==1.1.4",
    "sqlalchemy>=2.0.0",
    "alembic==1.8.1",
    "jsonschema==4.19",
    "tornado==6.5.5",
]
dynamic = ["version"]

[project.scripts]
miarka-processing-service = "miarka_processing_service.app:start"

[tool.setuptools.packages.find]
include = ["miarka_processing_service*"]

[tool.setuptools.dynamic]
version = {attr = "miarka_processing_service.__version__"}

[project.optional-dependencies]
dev = [
    "bumpversion==0.6.0",
    "flake8==7.3.0",
    "coverage==7.2.7",
    "Sphinx==5.3.0",
    "twine==4.0.2",
    "pytest==7.4.0",
    "pytest-runner==6.0.0",
    "pytest-asyncio==0.21.1",
    "pycodestyle==2.14.0",
    "mock",
]
