"""Add environment to job

Revision ID: d0a6d945cf99
Revises: 5fae4be42fbf
Create Date: 2019-04-24 12:01:41.331196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0a6d945cf99'
down_revision = '5fae4be42fbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('_environment', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', '_environment')
    # ### end Alembic commands ###
